org: randypitcherii
app: randy-pitcher-workspace-file-loader
service: randy-pitcher-workspace-file-loader

frameworkVersion: '3'

provider:
  name: aws
  region: us-west-2
  runtime: python3.11

  environment:
    OPENWEATHER_API_KEY: ${ssm(us-west-2):/randy_pitcher_workspace/serverless/openweather_api_key}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::randy-pitcher-workspace--aws--us-west-2/*"

functions:
  getWeatherData:
    handler: handler.lambda_handler
    events:
      # Invoke Lambda function every 10 minute
      - schedule: rate(5 minutes)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: False